config/routes.rb
Rails.application.routes.draw do
  resources :urlexplorers

  root "urlexplorers#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/urlexplorer.rb
require 'open-uri'
class Urlexplorer < ApplicationRecord
  validate :url_must_be_valid
  before_commit :get_content_and_parse_and_store, on: :create

  def url_must_be_valid
    if !is_valid_url(url)
      errors.add(:url, "This is not a valid URL. Please enter a correct url")
    end
  end

  def is_valid_url(value)
    uri = URI.parse(value)
    uri.is_a?(URI::HTTP) && !uri.host.nil?
  rescue URI::InvalidURIError
    false
  end

  def get_content_and_parse_and_store
    Rails.logger.debug { "The URL is #{self.url}" }
    file = open(self.url)
    self.update_attribute(:content,file.read)
    document = Nokogiri::HTML(self.content)
    parsed_data = Hash.new
    h1s_array = Array.new
    document.search('h1').each do |current|
      h1s_array << current.text
      puts current.text
    end
    parsed_data['h1'] = h1s_array
    h2s_array = Array.new
    document.search('h2').each do |current|
      h2s_array << current.text
      puts current.text
    end
    parsed_data['h2'] = h2s_array
    h3s_array = Array.new
    document.search('h3').each do |current|
      h3s_array << current.text
      puts current.text
    end
    parsed_data['h3'] = h3s_array

    link_urls = Array.new
    document.search('a').each do |current|
      link_urls << current.attribute('href').to_s
      puts current.attribute('href').to_s
    end
    parsed_data['link_urls'] = link_urls
    self.update_attribute(:parsed_headers, parsed_data.to_json)
    self.update_attribute(:is_parsing_done, true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urlexplorers_controller.rb
require 'open-uri'
class UrlexplorersController < ApplicationController
  before_action :set_urlexplorer, only: [:show, :edit, :update, :destroy]

  # GET /urlexplorers
  # GET /urlexplorers.json
  def index
    @urlexplorers = Urlexplorer.all
  end

  # GET /urlexplorers/1
  # GET /urlexplorers/1.json
  def show
  end

  # GET /urlexplorers/new
  def new
    @urlexplorer = Urlexplorer.new
  end

  # GET /urlexplorers/1/edit
  def edit
  end

  # POST /urlexplorers
  # POST /urlexplorers.json
  def create
    @urlexplorer = Urlexplorer.new(urlexplorer_params)

    respond_to do |format|
      if @urlexplorer.save
        format.html { redirect_to @urlexplorer, notice: 'Url was successfully stored and parsed.' }
        format.json { render :show, status: :created, location: @urlexplorer }
      else
        format.html { render :new }
        format.json { render json: @urlexplorer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urlexplorers/1
  # PATCH/PUT /urlexplorers/1.json
  def update
    respond_to do |format|
      if @urlexplorer.update(urlexplorer_params)
        format.html { redirect_to @urlexplorer, notice: 'Urlexplorer was successfully updated.' }
        format.json { render :show, status: :ok, location: @urlexplorer }
      else
        format.html { render :edit }
        format.json { render json: @urlexplorer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urlexplorers/1
  # DELETE /urlexplorers/1.json
  def destroy
    @urlexplorer.destroy
    respond_to do |format|
      format.html { redirect_to urlexplorers_url, notice: 'Urlexplorer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_urlexplorer
      @urlexplorer = Urlexplorer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def urlexplorer_params
      params.require(:urlexplorer).permit(:url, :content, :parsed_headers, :is_parsing_done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urlexplorers_helper.rb
module UrlexplorersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Getlines</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <%= yield %>
  </body>
</html>

app/views/urlexplorers/_form.html.erb
<%= form_for(urlexplorer) do |f| %>
  <% if urlexplorer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(urlexplorer.errors.count, "error") %> prohibited this urlexplorer from being saved:</h2>

      <ul>
      <% urlexplorer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :url, placeholder:'Enter the url to parse', autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Parse", class: "btn btn-primary btn-lg"%>
  </div>
<% end %>

app/views/urlexplorers/edit.html.erb
<h1>Editing Urlexplorer</h1>

<%= render 'form', urlexplorer: @urlexplorer %>

<%= link_to 'Show', @urlexplorer %> |
<%= link_to 'Back', urlexplorers_path %>

app/views/urlexplorers/index.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <h1>Urlexplorers</h1>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Url</th>
          <th>Parsed headers</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @urlexplorers.each do |urlexplorer| %>
          <tr>
            <td><%= urlexplorer.url %></td>
            <td><%= urlexplorer.parsed_headers %></td>
            <td><%= link_to 'Show', urlexplorer %></td>
            <td><%= link_to 'Edit', edit_urlexplorer_path(urlexplorer) %></td>
            <td><%= link_to 'Destroy', urlexplorer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Urlexplorer', new_urlexplorer_path, class: "btn btn-primary btn-lg" %>
    <br>
    <br>
  </div>
</div>

app/views/urlexplorers/new.html.erb
<main role="main" class="container">
  <div class="jumbotron">
    <h3>Parse a URL</h3>

    <%= render 'form', urlexplorer: @urlexplorer %>

    <%= link_to 'Back', urlexplorers_path %>

  </div>
</main>

app/views/urlexplorers/show.html.erb
<div class="container">
  <div class="row">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Url:</strong>
      <%= @urlexplorer.url %>
    </p>

    <p>
      <strong>Parsed headers:</strong>
      <%= @urlexplorer.parsed_headers %>
    </p>
    <%= link_to 'Edit', edit_urlexplorer_path(@urlexplorer) %> |
    <%= link_to 'Back', urlexplorers_path %>

  </div>
</div>